import sushi from "./Components/Sushi/Sushi";


export type productType = {
    name: string,
    description: string,
    src: string,
    price: number,
    weight: number,
};

export type allProductsType = {
    sushi: Array<productType>,
    woks: Array<productType>,
    soups: Array<productType>,
    pizza: Array<productType>,
    salads: Array<productType>,
    burgers: Array<productType>,
    garnish: Array<productType>,
    sets: Array<productType>,
    drinks: Array<productType>
}

export const allProducts: allProductsType= {
    sushi: [
        {
            name: 'С лососем',
            description: 'Рис, лосось',
            src: '/sushi/с лососем.jpg',
            price: 80,
            weight: 60,
        },
        {
            name: 'С угрем',
            description: 'Рис, угорь',
            src: '/sushi/с угрем.jpg',
            price: 80,
            weight: 50,
        },
        {
            name: 'С креветками',
            description: 'Рис, креветки',
            src: '/sushi/с креветками.jpg',
            price: 80,
            weight: 50,
        },
        {
            name: 'С тунцом',
            description: 'Рис, тунец',
            src: '/sushi/с тунцом.jpg',
            price: 79,
            weight: 50,
        },
        {
            name: 'Острый с лососем',
            description: 'Рис, лосось, спайс соус',
            src: '/sushi/острый с лососем.jpg',
            price: 89,
            weight: 80,
        },
        {
            name: 'Острый с угрем',
            description: 'Рис, угорь, спайс соус',
            src: '/sushi/острый с угрем.jpg',
            price: 89,
            weight: 70,
        },
        {
            name: 'Острый с креветками',
            description: 'Рис, креветки спайс соус',
            src: '/sushi/острый с креветками.jpg',
            price: 89,
            weight: 70,
        },
        {
            name: 'Острый с тунцом',
            description: 'Рис, тунец, спайс соус',
            src: '/sushi/острый с тунцом.jpg',
            price: 89,
            weight: 70,
        },
    ],
    woks: [
        {
            name: 'Удон пшеничный с курицей',
            description: 'Курица, болгарский перец, морковь, красный лук, зеленый лук, фасоль, кунжут',
            src: '/woks/удон пшеничный с курицей.jpg',
            price: 180,
            weight: 290,
        },
        {
            name: 'Удон пшеничный с креветкой',
            description: 'Креветки, болгарский перец, морковь, красный лук, зеленый лук, фасоль, кунжут',
            src: '/woks/удон пшеничный с креветкой.jpg',
            price: 240,
            weight: 290,
        },
        {
            name: 'Удон пшеничный с морепродуктами',
            description: 'Морепродукты, болгарский перец, морковь, красный лук, зеленый лук, фасоль, кунжут',
            src: '/woks/удон пшеничный с морепродуктами.jpg',
            price: 260,
            weight: 290,
        },
        {
            name: 'Удон пшеничный с лососем',
            description: 'Лосось, болгарский перец, морковь, красный лук, зеленый лук, фасоль, кунжут',
            src: '/woks/удон пшеничный с лососем.jpg',
            price: 280,
            weight: 290,
        },
        {
            name: 'Соба – гречневый с курицей',
            description: 'Курица, болгарский перец, морковь, красный лук, зеленый лук, фасоль, кунжут',
            src: '/woks/соба – гречневый с курицей.jpg',
            price: 180,
            weight: 290,
        },
        {
            name: 'Соба – гречневый с креветкой ',
            description: 'Креветки, болгарский перец, морковь, красный лук, зеленый лук, фасоль, кунжут',
            src: '/woks/соба – гречневый с креветкой .jpg',
            price: 240,
            weight: 290,
        },
        {
            name: 'Соба – гречневый с морепродуктами',
            description: 'Морепродукты, болгарский перец, морковь, красный лук, зеленый лук, фасоль, кунжут',
            src: '/woks/соба – гречневый с морепродуктами.jpg',
            price: 260,
            weight: 290,
        },
        {
            name: 'Соба – гречневый с лососем',
            description: 'Лосось, болгарский перец, морковь, красный лук, зеленый лук, фасоль, кунжут',
            src: '/woks/соба – гречневый с лососем.jpg',
            price: 280,
            weight: 290,
        },
        {
            name: 'Харусаме с курицей',
            description: 'Курица, болгарский перец, красный лук, зеленый лук, фасоль, кунжут',
            src: '/woks/харусаме с курицей.jpg',
            price: 10,
            weight: 290,
        },
        {
            name: 'Харусаме с креветкой',
            description: 'Креветки, болгарский перец, красный лук, зеленый лук, фасоль, кунжут',
            src: '/woks/харусаме с креветкой.jpg',
            price: 250,
            weight: 290,
        },
        {
            name: 'Харусаме с морепродуктами',
            description: 'Морепродукты, болгарский перец, красный лук, зеленый лук, фасоль, кунжут',
            src: '/woks/харусаме с морепродуктами.jpg',
            price: 270,
            weight: 290,
        },
        {
            name: 'Харусаме с лососем',
            description: 'Лосось, болгарский перец, красный лук, зеленый лук, фасоль, кунжут',
            src: '/woks/харусаме с лососем.jpg',
            price: 290,
            weight: 290,
        },
    ],
    soups: [
        {
            name: 'Том-ям',
            description: 'Креветка, лимон грас, кор.имбиря, лайм, паста Том, перец чили, грибы вешенки, рис',
            src: '/soups/том-ям.jpg',
            price: 360,
            weight: 340,
        },
        {
            name: 'Том-ям на кокосовом молоке',
            description: 'Креветка, лимон грас, кор.имбиря, лайм, паста Том, перец чили, грибы вешенки, рис, кокосовое молоко',
            src: '/soups/том-ям на кокосовом молоке.jpg',
            price: 390,
            weight: 340,
        },
        {
            name: 'Суимона',
            description: 'Креветка, ваками, сыр тофу, лук, кунжут',
            src: '/soups/суимона.jpg',
            price: 180,
            weight: 300,
        },
        {
            name: 'Мисо',
            description: 'Лосось, хандаш, ваками, сыр тофу, лук, кунжут',
            src: '/soups/мисо.jpg',
            price: 180,
            weight: 300,
        },
        {
            name: 'Креп-суп грибной',
            description: '',
            src: '/soups/креп-суп грибной.jpg',
            price: 230,
            weight: 30,
        },
        {
            name: 'Крем-суп с лососем',
            description: '',
            src: '/soups/крем-суп с лососем.jpg',
            price: 260,
            weight: 30,
        },
    ],
    pizza: [
        {
            name: 'Маргарита',
            description: 'Сыр моцарелла, помидор, пряные травы, соус томатный',
            src: '/pizza/маргарита.jpg',
            price: 300,
            weight: 540,
        },
        {
            name: 'Смесь сыров',
            description: 'Дорблю, пармезан, моцарелла, чедерр, соус томатный',
            src: '/pizza/смесь сыров.jpg',
            price: 380,
            weight: 540,
        },
        {
            name: 'Пепперони',
            description: 'Моцарелла, пепперони, соус томатный',
            src: '/pizza/пепперони.jpg',
            price: 399,
            weight: 510,
        },
        {
            name: 'Ханская',
            description: 'Моцарелла, пепперони, куриное филе, перец болгарский, холопеньо, соус томатный',
            src: '/pizza/ханская.jpg',
            price: 430,
            weight: 590,
        },
        {
            name: 'Мясной хан',
            description: 'Моцарелла, соус томатный, с/к колбаса, ветчина, пепперони, салями',
            src: '/pizza/мясной хан.jpg',
            price: 449,
            weight: 570,
        },
        {
            name: 'Цыпленок с чесноком',
            description: 'Куриное филе, шампиньон, помидоры, помидоры, моцарелла, сливки, суш.чеснок, соус томатный',
            src: '/pizza/цыпленок с чесноком.jpg',
            price: 439,
            weight: 680,
        },
        {
            name: 'Ветчина, грибы',
            description: 'Моцарелла, соус томатный, помидоры',
            src: '/pizza/ветчина, грибы.jpg',
            price: 390,
            weight: 580,
        },
        {
            name: 'Морская',
            description: 'Моцарелла, соус томатный, креветка, кальмары, осьминог, маслины, помидоры',
            src: '/pizza/морская.jpg',
            price: 480,
            weight: 650,
        },
        {
            name: 'Барбекю',
            description: 'Куриное филе, ветчина, лук красный, моцарелла, соус барбекю',
            src: '/pizza/барбекю.jpg',
            price: 419,
            weight: 510,
        },
        {
            name: 'Цезарь ',
            description: 'Помидор, куриное филе, айсберг, соус цезарь, моцарелла, пармезан',
            src: '/pizza/цезарь .jpg',
            price: 459,
            weight: 700,
        },
        {
            name: 'Вегетарианская',
            description: 'Пряные травы, помидоры, болгарский перец, шампиньоны, маслины, моцарелла, соус томатный',
            src: '/pizza/вегетарианская.jpg',
            price: 389,
            weight: 580,
        },
        {
            name: 'Мясная сборная',
            description: 'Помидоры, моцарелла, куриное филе, ветчина, с/к колбаса, пепперони, соус томатный',
            src: '/pizza/мясная сборная.jpg',
            price: 479,
            weight: 610,
        },
    ],
    salads: [
        {
            name: 'Цезарь с курицей',
            description: 'Жареная курица, айсберг, помидор, яблоко, маслины, оливки, соус цезарь, черри, переп.яйца, сыр пармезан, гренки',
            src: '/salads/цезарь с курицей.jpg',
            price: 289,
            weight: 310,
        },
        {
            name: 'Цезарь с креветкой',
            description: 'Креветки, айсберг, помидор, яблоко, маслины, оливки, соус цезарь, черри, переп.яйца, сыр пармезан, гренки',
            src: '/salads/цезарь с креветкой.jpg',
            price: 310,
            weight: 310,
        },
        {
            name: 'Цезарь с лососем',
            description: 'Лосось, айсберг, помидор, яблоко, маслины, оливки, соус цезарь, черри, переп.яйца, сыр пармезан, гренки',
            src: '/salads/цезарь с лососем.jpg',
            price: 309,
            weight: 310,
        },
        {
            name: 'Греческий',
            description: 'Огурец, помидор, болгарский перец, красный лук, соус греческий, сыр фетаки, маслины, оливки',
            src: '/salads/греческий.jpg',
            price: 279,
            weight: 310,
        },
        {
            name: 'Чука',
            description: 'Салат чука, ореховый соус, лимон, кунжут',
            src: '/salads/чука.jpg',
            price: 149,
            weight: 160,
        },
    ],
    burgers: [
        {
            name: 'Бургер настоящий',
            description: 'Говяжья котлета, пшеничная булочка, гор.американская, красный лук, майонез, маринованный огурец, соус барбекю, помидор, сыр чиз',
            src: '/burgers/бургер настоящий.jpg',
            price: 199,
            weight: 250,
        },
        {
            name: 'Бургер хан',
            description: 'Говяжья котлета, пшеничная булочка, гор.американская, красный лук, майонез, маринованный огурец, лист салата, соус барбекю, помидор',
            src: '/burgers/бургер хан.jpg',
            price: 199,
            weight: 250,
        },
        {
            name: 'Бургер сити',
            description: 'Говяжья котлета, пшеничная булочка, гор.американская, красный лук, майонез, маринованный огурец, лист салата,  соус барбекю, помидор, яйца',
            src: '/burgers/бургер сити.jpg',
            price: 199,
            weight: 250,
        },
    ],
    garnish: [
        {
            name: 'Картофель-фри',
            description: 'Картофель, специи',
            src: '/garnish/картофель-фри.jpg',
            price: 129,
            weight: 200,
        },
        {
            name: 'Картофель по-деревенски',
            description: 'Картофель, специи',
            src: '/garnish/картофель по-деревенски.jpg',
            price: 129,
            weight: 200,
        },
        {
            name: '',
            description: 'Куриное филе, специи',
            src: '/garnish/.jpg',
            price: 159,
            weight: 200,
        },
    ],
    sets: [
        {
            name: 'Сет «Итальяно»',
            description: 'Пиццы "Маргарита", "Пепперони", "Мясной хан"',
            src: '/sets/сет «итальяно».jpg',
            price: 799,
            weight: 2100,
        },
        {
            name: 'Сет «Для двоих»',
            description: 'Филадельфия классик, Премиум, Ролл с огурцом, Суши с лососем',
            src: '/sets/сет «для двоих».jpg',
            price: 599,
            weight: 659,
        },
        {
            name: 'Сет «Оогоо»',
            description: 'Канада, Калифорния, Ролл с креветкой, Филадельфия с огурцом',
            src: '/sets/сет «оогоо».jpg',
            price: 799,
            weight: 850,
        },
        {
            name: 'Сет «Огонь»',
            description: 'Горячий с лососем, Горячий с курицей, Горячий с креветкой, Запеченный с креветкой, Запеченный с угрем',
            src: '/sets/сет «огонь».jpg',
            price: 1099,
            weight: 400,
        },
        {
            name: 'Сет «Раз на раз»',
            description: ' Сливочная калифорния, Пантера, Татмикс',
            src: '/sets/сет «раз на раз».jpg',
            price: 619,
            weight: 750,
        },
        {
            name: 'Сет «Всем хватит»',
            description: 'Майями, Пантера, Филадельфия классик, Канада чиз, Горячий с курицей, Тайка, Сливочная калифорния, Эби маки, Запеченная с креветкой',
            src: '/sets/сет «всем хватит».jpg',
            price: 2199,
            weight: 2250,
        },
    ],
    drinks: [
        {
            name: 'Pepsi',
            description: '',
            src: '/drinks/pepsi.jpg',
            price: 80,
            weight: 500,
        },
        {
            name: 'Pepsi ж/б',
            description: '',
            src: '/drinks/pepsi ж/б.jpg',
            price: 70,
            weight: 330,
        },
        {
            name: 'Mirinda',
            description: '',
            src: '/drinks/mirinda.jpg',
            price: 80,
            weight: 500,
        },
        {
            name: 'Mirinda ж/б',
            description: '',
            src: '/drinks/mirinda ж/б.jpg',
            price: 70,
            weight: 330,
        },
        {
            name: '7 Up',
            description: '',
            src: '/drinks/7 up.jpg',
            price: 80,
            weight: 500,
        },
        {
            name: '7 Up ж/б',
            description: '',
            src: '/drinks/7 up ж/б.jpg',
            price: 70,
            weight: 330,
        },
        {
            name: 'Adrenaline Rush',
            description: '',
            src: '/drinks/adrenaline rush.jpg',
            price: 150,
            weight: 500,
        },
        {
            name: 'Adrenaline Rush ж/б',
            description: '',
            src: '/drinks/adrenaline rush ж/б.jpg',
            price: 100,
            weight: 250,
        },
        {
            name: 'Холодного чай Lipton (зеленый, персик, лимон)',
            description: '',
            src: '/drinks/холодного чай lipton (зеленый, персик, лимон).jpg',
            price: 120,
            weight: 1000,
        },
        {
            name: 'Холодного чай Lipton (зеленый, персик, лимон)',
            description: '',
            src: '/drinks/холодного чай lipton (зеленый, персик, лимон).jpg',
            price: 90,
            weight: 500,
        },
        {
            name: 'Холодного чай Lipton (зеленый, персик, лимон) ж/б',
            description: '',
            src: '/drinks/холодного чай lipton (зеленый, персик, лимон) ж/б.jpg',
            price: 70,
            weight: 250,
        },
        {
            name: 'Aqua Minerale',
            description: '',
            src: '/drinks/aqua minerale.jpg',
            price: 80,
            weight: 1000,
        },
        {
            name: 'Aqua Minerale',
            description: '',
            src: '/drinks/aqua minerale.jpg',
            price: 60,
            weight: 500,
        },
        {
            name: 'Aqua Minerale Active',
            description: '',
            src: '/drinks/aqua minerale active.jpg',
            price: 100,
            weight: 1000,
        },
        {
            name: 'Aqua Minerale Active',
            description: '',
            src: '/drinks/aqua minerale active.jpg',
            price: 80,
            weight: 600,
        },
        {
            name: 'Клюквенный морс',
            description: '',
            src: '/drinks/клюквенный морс.jpg',
            price: 80,
            weight: 500,
        },
    ]
}